version: '2'
services:
  api:
    build: .
    ports:
     - "80:80"
    depends_on:
     - redis
     - databases
    restart: always
  redis:
    image: redis
    restart: always
  orientdb:
    image: databases
    restart: always
    ports:
         - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: 'tela'